### ISSUE TITLE
Respawn mechanics are broken when using this mod

### ISSUE THREAD

**Issue by DarSitam** [natebouchat/ReturnsDroneRevive#1]
This includes :

- Dio
- ZetAspects's Artifact of Revival (respawn after a teleporter event ends)

This is something i wanted for so long, i hope it'll be fixed one day

**Comment by Hyenate** [comment]
Did it respawn you as a drone even though you had a Dio? The mod shouldn't activate while a player has a Dio/Pluripotent Larva, but I can see if something isn't being checked right.

Similarly, what happened with the Artifact of Revival mod? I assume it either respawned you as a drone or kept you as a drone after teleporter, but it should respawn you as a survivor next stage. I can look into getting compatibility with other revival mods, but I can't say for sure how feasible this is at the moment.

**Comment by DarSitam** [comment]
> Did it respawn you as a drone even though you had a Dio? The mod shouldn't activate while a player has a Dio/Pluripotent Larva, but I can see if something isn't being checked right.

I did respawn as a drone, even tho Dio was (kinda) consumed

![image](https://github.com/natebouchat/ReturnsDroneRevive/assets/106157297/874185b7-6ae4-4246-924b-fba73d53b233)

> Similarly, what happened with the Artifact of Revival mod? I assume it either respawned you as a drone or kept you as a drone after teleporter, but it should respawn you as a survivor next stage. I can look into getting compatibility with other revival mods, but I can't say for sure how feasible this is at the moment.

The dead player stayed as a drone. I can understand than this specific artifact might be redundant with this mod

BTW i should add that 1) I used [this mod](https://thunderstore.io/package/Nuxlar/MultiplayerModTesting/) to test multiplayer functionnality offline, and trying to respawn using [Aerolt](https://thunderstore.io/package/Lodington/Aerolt/) keeps the dead player as a drone

**Comment by Hyenate** [comment]
The Dios issue should be fixed now. Thanks for letting me know about this.

As for compatibility with other revival mods, as far as I know, I have no way of checking if the player is being respawned outside of my own scripts. Sorry about that.

**Comment by DarSitam** [comment]
Ok so, after some tests :

- Respawning as Dio works
- Respawning via Aerolt makes us respawn as the proper survivor
- The artifact of revival still doesnt work, but that's to be expected

I'll close the issue, keep up the good work !
